### PR TITLE
feat: literal

### PR DESCRIPTION
**Pull request by Ghibranalj**
i implemented literal

where:
its literal when on root and,
its string on depth > 0

One thing is still unclear in thes spec: should we preserve the text on folding literal

### CODE REVIEW

**Review by dnswd — APPROVED** [review]
LGTM

**Comment by mustafasegf** [comment]
this introduce issue when use | literal and there's white space. leading whitespace in double quotes flow are ignored https://yaml.org/spec/1.2.2/#65-line-folding

**Comment by mustafasegf** [comment]
one way to fix this is to have one line of double quote flow and convert newline to newline '\n' literal

**Comment by Ghibranalj** [comment]
> one way to fix this is to have one line of double quote flow and convert newline to newline '\n' literal

can you give me an example literal?

**Comment by Ghibranalj** [comment]
@mustafasegf  there is a problem with the ast.
if i implemented it like that the indentation will be treated as spaces.
I think im gonna merge this for the sake of progress.

**Pull request merged**
